//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MailCore/ECMessageHeaders-Protocol.h>

@class NSArray, NSString;

@protocol ECMutableMessageHeaders <ECMessageHeaders>
- (void)setAddressListForTo:(NSArray *)arg1;
- (void)setAddressListForSender:(NSArray *)arg1;
- (void)setAddressList:(NSArray *)arg1 forKey:(NSString *)arg2;
- (void)setHeader:(id)arg1 forKey:(NSString *)arg2;
- (void)removeHeaderForKey:(NSString *)arg1;
@end

