//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCMessageDataSource.h"

@class IMAPCommandPipeline, IMAPDownloadCache, IMAPMessage, IMAPServerInterface, MCMimePart, NSArray, NSDictionary, NSIndexSet, NSMutableArray, NSMutableDictionary, NSSet, NSString;

@protocol IMAPMessageDataSource <MCMessageDataSource>
@property(readonly, copy) NSMutableArray *messagesBeingAdded;
@property BOOL supportsModificationSequences;
@property(nonatomic) unsigned long long allegedHighestModificationSequence;
@property(nonatomic) unsigned int uidNextStatus;
@property(readonly, nonatomic) unsigned int maximumRemoteID;
@property(readonly, nonatomic) IMAPDownloadCache *downloadCache;
@property(readonly, nonatomic) IMAPCommandPipeline *fetchPipeline;
@property(readonly, nonatomic) unsigned long long totalCountOfMessages;
@property(readonly, nonatomic) BOOL isAllMailMailbox;
@property(readonly, nonatomic) BOOL isInbox;
@property(readonly, copy) NSString *mailboxName;
@property(readonly, nonatomic) id <IMAPAccount> account;
- (NSArray *)messagesWithRemoteIDs:(NSArray *)arg1;
- (NSArray *)duplicateRemoteIDs;
- (NSArray *)messagesWithRowIDs:(NSArray *)arg1;
- (id <IMAPPersistedMessage>)messageWithDefaultLoadOptionsAndRowID:(long long)arg1;
- (void)removeAllLocalMessages;
- (void)setUidValidityStatus:(unsigned int)arg1;
- (unsigned int)uidValidityStatus;
- (void)setUidNextStatusIfNeeded:(unsigned int)arg1;
- (void)setComputedHighestModificationSequence:(unsigned long long)arg1;
- (void)syncEngineDidFinish;
- (void)syncEngineDidStart;
- (NSDictionary *)newDictionaryForLocalFlags:(unsigned int)arg1 serverFlags:(unsigned int)arg2 existingDictionary:(NSDictionary *)arg3;
- (NSArray *)setFlagsFromDictionary:(NSDictionary *)arg1 forMessages:(NSArray *)arg2 updatingServer:(BOOL)arg3;
- (void)async_setFlagsFromDictionary:(NSDictionary *)arg1 forMessages:(NSArray *)arg2 updatingServer:(BOOL)arg3;
- (BOOL)messageHasBeenDeleted:(id <IMAPPersistedMessage>)arg1;
- (void)compactMessages:(NSArray *)arg1;
- (NSSet *)fetchAndCacheBodyDataForMessages:(NSSet *)arg1 withServerInterface:(IMAPServerInterface *)arg2;
- (void)addMessages:(NSArray *)arg1 oldMessagesByNewMessage:(NSMutableDictionary *)arg2;
- (BOOL)hasValidCacheFileForMessage:(IMAPMessage *)arg1;
- (BOOL)hasCacheFileForMessage:(id <IMAPPersistedMessage>)arg1 part:(MCMimePart *)arg2;
- (BOOL)hasCacheFileForMessage:(id <IMAPPersistedMessage>)arg1;
- (NSArray *)copyIncompleteMessages;
- (NSArray *)copyMessagesWithoutValidUids;
- (NSArray *)getDetailsForMessagesWithRemoteIDs:(NSIndexSet *)arg1 waitForWrites:(BOOL)arg2;
- (unsigned long long)totalCountAndUnseenCount:(unsigned long long *)arg1 adjustedUnreadCount:(unsigned long long *)arg2;

@optional
- (NSArray *)setGmailLabelsFromDictionary:(NSDictionary *)arg1 forMessages:(NSArray *)arg2 updatingServer:(BOOL)arg3;
- (void)async_setGmailLabelsFromDictionary:(NSDictionary *)arg1 forMessages:(NSArray *)arg2 updatingServer:(BOOL)arg3;
@end

