//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCRemoteStoreAccount.h"

@class IMAPConnection, IMAPMailbox, IMAPQuotaRoot, IMAPResponse, IMAPServerInterface, IMAPTaskManager, MCError, NSArray, NSDictionary, NSString;

@protocol IMAPAccount <MCRemoteStoreAccount>
@property(copy) NSString *serverPathPrefix;
@property BOOL supportsQuickResynchronization;
@property(readonly, copy, nonatomic) NSArray *allBackgroundMailboxNames;
@property(readonly) BOOL shouldMoveDeletedMessagesToTrash;
@property(readonly) BOOL allowsPartialDownloads;
@property(readonly) id <IMAPOfflineCache> offlineCache;
@property(copy) NSDictionary *serverID;
@property(retain) MCError *connectionError;
@property BOOL useIDLEIfAvailable;
@property(readonly, nonatomic) IMAPTaskManager *taskManager;
- (void)setSupportsModificationSequences:(BOOL)arg1 forMailboxName:(NSString *)arg2;
- (id <MCMailbox>)mailboxForName:(NSString *)arg1;
- (id <IMAPMessageDataSource>)dataSourceForMailboxName:(NSString *)arg1;
- (void)recoverFromConnectionlessStateWithServerInterface:(IMAPServerInterface *)arg1;
- (void)setSeparatorCharIfNeededWithServerInterface:(IMAPServerInterface *)arg1;
- (void)backgroundFetchCompleted;
- (IMAPQuotaRoot *)quotaRootForName:(NSString *)arg1 createIfNeeded:(BOOL)arg2;
- (BOOL)handleResponseCodeFromResponse:(IMAPResponse *)arg1;
- (IMAPMailbox *)IMAPMailboxForMailboxName:(NSString *)arg1 createIfNeeded:(BOOL)arg2;
- (NSString *)separatorCharFetchIfNeeded:(BOOL)arg1;

@optional
- (void)detectAllMailMailboxWithConnection:(IMAPConnection *)arg1;
- (id <MCGmailLabel>)gmailLabelWithName:(NSString *)arg1;
@end

