//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Mail/MFLibraryUpgradeStep.h>

@class NSDictionary;

@interface MFResetPartsHaveBeenCachedUpgradeStep : MFLibraryUpgradeStep
{
    NSDictionary *_mailboxFileSystemPathsByDatabasePaths;
}

+ (BOOL)requiredAfterBackbooting;
+ (unsigned long long)targetVersion;
+ (unsigned long long)minimumAffectedVersion;
@property(readonly, copy, nonatomic) NSDictionary *mailboxFileSystemPathsByDatabasePaths; // @synthesize mailboxFileSystemPathsByDatabasePaths=_mailboxFileSystemPathsByDatabasePaths;
- (void).cxx_destruct;
- (void)run;
- (id)initWithSQLHandle:(id)arg1;
- (id)initWithSQLHandle:(id)arg1 mailboxFileSystemPathsByDatabasePaths:(id)arg2;

@end

