//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MUICollectionCellView, NSString, NSVisualEffectView, SubjectHeaderTextView;

@interface SubjectHeaderViewController : NSViewController
{
    BOOL _hidden;
    NSVisualEffectView *_subjectTextViewContainer;
    SubjectHeaderTextView *_subjectTextView;
}

+ (id)_stringAttributes;
@property(retain, nonatomic) SubjectHeaderTextView *subjectTextView; // @synthesize subjectTextView=_subjectTextView;
@property(retain, nonatomic) NSVisualEffectView *subjectTextViewContainer; // @synthesize subjectTextViewContainer=_subjectTextViewContainer;
- (void).cxx_destruct;
@property(nonatomic) BOOL hidden;
@property(copy, nonatomic) NSString *subject;
- (void)viewDidLoad;
@property(retain) MUICollectionCellView *view;
- (void)loadView;

@end

