//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MailCore/MCProgressEntry.h>

@interface MCCheckingForMailProgressEntry : MCProgressEntry
{
    BOOL _foundNewUnreadMessageInInbox;
    unsigned long long _foundMessages;
}

+ (id)keyPathsForValuesAffectingStatusText;
@property(nonatomic) BOOL foundNewUnreadMessageInInbox; // @synthesize foundNewUnreadMessageInInbox=_foundNewUnreadMessageInInbox;
@property(nonatomic) unsigned long long foundMessages; // @synthesize foundMessages=_foundMessages;
- (double)finishDelay;
- (void)refreshValues;
- (id)observedProgressKeypaths;
- (id)progressSlice;
- (BOOL)indeterminate;
- (id)statusText;
- (id)progressName;

@end

