//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface ComposeHeaderRowView : NSView
{
    BOOL _drawsFullWidthSeparator;
}

@property(nonatomic) BOOL drawsFullWidthSeparator; // @synthesize drawsFullWidthSeparator=_drawsFullWidthSeparator;
- (void)drawRect:(struct CGRect)arg1;

@end

