//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MCAttachment, MFAttachmentViewController, NSMenuItem, NSPasteboard, NSString, WebArchive, WebView;

@protocol EditingMessageWebViewDelegate <NSObject>
@property(readonly, nonatomic) BOOL selectionIsInList;
@property(nonatomic) BOOL allowsRichText;
@property(readonly, nonatomic) BOOL allowQuoting;
- (BOOL)validateUserInterfaceItem:(id <NSValidatedUserInterfaceItem>)arg1;
- (BOOL)validateMenuItem:(NSMenuItem *)arg1;
- (void)convertToBulletedList:(id)arg1;
- (void)convertToNumberedList:(id)arg1;
- (void)decreaseListNestingLevel:(id)arg1;
- (void)increaseListNestingLevel:(id)arg1;
- (void)removeSelectedLink;
- (void)editLink;

@optional
- (void)webViewWillInsertContentsOfWebpage:(WebView *)arg1;
- (BOOL)webViewShouldReplaceSelectionWithContentsOfWebpage:(WebView *)arg1;
- (void)webViewMainDocumentBaseURIDidChange:(WebView *)arg1;
- (BOOL)webView:(WebView *)arg1 canInsertFromPasteboard:(NSPasteboard *)arg2 forDrag:(BOOL)arg3;
- (BOOL)webView:(WebView *)arg1 canInsertFromDraggingInfo:(id <NSDraggingInfo>)arg2;
- (WebArchive *)webView:(WebView *)arg1 shouldReplaceSelectionWithWebArchive:(WebArchive *)arg2 givenAction:(long long)arg3;
- (void)webView:(WebView *)arg1 willRemoveMailAttachment:(MFAttachmentViewController *)arg2;
- (void)webView:(WebView *)arg1 didAddMailAttachment:(MCAttachment *)arg2;
- (void)webView:(WebView *)arg1 willReplaceSelectionWithFragment:(id *)arg2 pasteboard:(NSPasteboard *)arg3 type:(NSString *)arg4 options:(unsigned long long *)arg5;
- (void)webViewDidEndLiveResize:(WebView *)arg1;
- (void)webViewWillStartLiveResize:(WebView *)arg1;
- (void)removeAttachment:(MCAttachment *)arg1;
@end

