//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSInspectorBarClient.h"
#import "NSTextInputClient.h"

@protocol MailInspectorBarClient <NSInspectorBarClient, NSTextInputClient>
- (BOOL)isActive;
@end

