//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@protocol MessageFilterDelegate <NSObject>
- (void)postNotifications:(NSArray *)arg1;
- (void)storesLoaded:(BOOL)arg1;
- (void)storesDidOpen;
- (void)setFilteredMessages:(NSArray *)arg1 totalMessageCount:(unsigned long long)arg2 originalMessageByMessageID:(NSDictionary *)arg3 messageCopiesByMessageID:(NSDictionary *)arg4;
@end

