//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SGRealtimeEvent, SuggestedEventPopoverController;

@protocol SuggestedEventPopoverControllerDelegate <NSObject>
- (void)commitSuggestedEvents:(NSArray *)arg1;
- (void)commitSuggestedEvent:(SGRealtimeEvent *)arg1;
- (void)cancelSuggestedEventPopoverController:(SuggestedEventPopoverController *)arg1;
@end

