//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MessageList.h"

@class NSArray;

@protocol ThreadSupportingMessageList <MessageList>
@property(readonly, nonatomic) __weak id <ThreadedMessageListDelegate> delegate;
- (NSArray *)closeAllThreads;
- (NSArray *)closeThreads:(NSArray *)arg1;
- (NSArray *)openAllThreads;
- (NSArray *)openThreads:(NSArray *)arg1;
@end

