//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MFEWSAccount;

@interface _MFEWSAutodiscoveryTimerTarget : NSObject
{
    MFEWSAccount *_account;
}

@property(nonatomic) __weak MFEWSAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)kickOffReautodiscovery:(id)arg1;

@end

