//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Mail/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateLastViewed : MFMessageSortingValue
{
    double _dateLastViewedAsTimeIntervalSince1970;
}

@property(nonatomic) double dateLastViewedAsTimeIntervalSince1970; // @synthesize dateLastViewedAsTimeIntervalSince1970=_dateLastViewedAsTimeIntervalSince1970;
- (id)description;

@end

