//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Mail/EDAccountFactory-Protocol.h>

@interface MFAccountFactory_macOS : NSObject <EDAccountFactory>
{
}

- (id)accountWithSystemAccount:(id)arg1;
- (id)accountWithIdentifier:(id)arg1;

@end

