//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Mail/MFMessageDeliverer.h>

@class MFSMTPAccount;

@interface MFSMTPDeliverer : MFMessageDeliverer
{
}

- (long long)deliverMessageHeaderData:(id)arg1 bodyData:(id)arg2 toRecipients:(id)arg3;
@property(retain, nonatomic) MFSMTPAccount *account;

@end

